fail('This is an error')